name: giphy
version: 0.1.0
author: Marcos Placona <hi@placona.co.uk>
description: An implementation of the Giphy API for Dart
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  http: any
  json: any
dev_dependencies:
  unittest: any
