name: giphy
version: 0.1.0
author: Marcos Placona <hi@placona.co.uk>
description: An implementation of the Giphy API for Dart
homepage: http://mplacona.github.io/giphy
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  http: '>=0.10.0 <=0.11.0+1'
dev_dependencies:
  unittest: any
